language: c
os:
 - linux
 - osx

script:
 - cd curves
 - bash test.sh
 - bash build.sh
 - cd build && make curves
 - ./curves
 - cd ../../linear-systems
 - bash test.sh
 - bash build.sh
 - cd build && make linear
 - ./linear