language: c
os:
 - linux
 - osx

script:
 - cd curves
 - bash test.sh 2> /dev/null
 - bash build.sh 
 - cd build && make curves
 - ./curves 2> /dev/null
 - cd ../../linear-systems
 - bash test.sh
 - bash build.sh
 - cd build && make linear
 - ./linear